### ISSUE TITLE
謝謝你的心得與筆記

### ISSUE THREAD

**Issue by azole** [boterasuo/git-workshop#1]
看到你的代辦事項真的很棒耶，筆記 -> 心得 -> 行動，你完全達到了做筆記的功用！

我自己認為學習任何一個領域，或者縮小一點，學習寫程式這件事，需要的是這三點「正確的學習方式」＋「願意努力花時間練習」＋「不害怕犯錯與挫折」，所以想在課程開始的時候，讓你們看看這部我自己獲益良多的影片，從你的紀錄，我看到的了很好的效果，新的一年，讓我們去把它達成吧！

說到年紀這件事，我想你的年紀應該沒有我大吧，大概人生中，總是會有一段時間，會去後悔自己當初做了/沒做什麼，但再過一段時間後，就會進入到，知道眼睛只能往前看了，沒有時間往後看了，我想你既然決定轉職，應該也是漸漸有了這樣的體悟。

看你的紀錄，你應該是偏向後端？ 我自己很喜歡這個領域喔，未來在學習上有任何想要討論的，都歡迎找我，即便是在課程結束後也是，歡迎一起討論、一起聊聊。

**Comment by boterasuo** [comment]
謝謝老師的回覆～～（抱歉一直忘記來回覆 issue） 
我的年紀已經逼近35歲了(汗)，雖然當初確實是有做好覺悟，但看著身邊的同學們大部分都未滿30歲，偶爾還是會有點不安～不過在老師的課堂中，總是又能獲得滿滿的熱誠、和繼續往前進的動能，覺得年齡好像不是那麼大的阻礙了（身體的老化和各種酸痛還比較需要擔心XD），總之真的很喜歡上小賴老師的課！
我是在做小專的過程中發現自己對資料庫和PHP滿有興趣的，練習設計 table schema 的過程莫名療癒，在寫PHP和資料庫互動的過程我也覺得很有趣，近期在做的爬蟲專案也覺得很好玩，不確定這樣算不算是偏向後端 XD，希望未來能把和資料庫相關的這塊、和比較底層的東西／原理弄得更熟一點～再請小賴老師多多指導了 : )

小專時練習畫的 ER-model（不過大專時需要再修改 XD）：
https://hackmd.io/@voG6V_BHRJ6JtH-Ixd8vLg/rkNbBlQat
希望修改好後有機會請小賴老師幫忙看看～～

**Comment by azole** [comment]
喔喔喔喔，歡迎加入後端的領域，最喜歡在前端班挖牆腳了，有任何問題都歡迎討論喔！

年紀真的不是問題，頭腦會愈用愈聰明喔，而且年紀比較大也有年紀比較大的優點，這個在我過去職場上跟帶的學生經常都能被驗證，重點在於，自己能不能找出這個優勢來～

**Comment by boterasuo** [comment]
謝謝小賴老師~辛苦您惹 今天又被我們綁架到六點 XD
認同頭腦會越用越聰明，雖然記憶力的部分反而...
希望之後我也能找到我的優勢，目前好像只有看不出年紀這個優勢（自己說哈哈哈）
也希望之後順利找到(後端的)工作後，有機會參加老師的讀書會～
